### ISSUE TITLE
Special case: Connect to two databases

### ISSUE THREAD

**Issue by Dubidubiduu** [PanCakeConnaisseur/user_backend_sql_raw#2]
Hello everyone,

I would love to connect to a Wordpress + CiviCrm System. Which means, user, email, pw lays in wordpress database and group settings lays in civicrm database.

1.) Is it possible to connect to two different databases with this app? Could this be a #feature?
2.) Are groups supported yet?

Greetz

**Comment by PanCakeConnaisseur** [comment]
1. This would imho complicate the architecture of the app, because it needs an additional level of indirection/lookup to decide which db to use for which query. Therefore I would not want to implement it, as it seems that your use case is an edge case.

2. Not yet. I am using Nextcloud groups personally.
