### ISSUE TITLE
"ILIKE" is not ANSI compliant SQL and is not supported by MySQL/MariaDB

### ISSUE THREAD

**Issue by oucil** [PanCakeConnaisseur/user_backend_sql_raw#28]
Like the title says, you're examples include SQL that is not ANSI compliant.  

**OLD:** SELECT fqda FROM users_fqda WHERE (fqda **ILIKE** :search) OR (display_name **ILIKE** :search)

Instead, I would suggest updating your docs to something like this to achieve the same results...

**NEW 1:** SELECT fqda FROM users_fqda WHERE (fqda COLLATE utf8mb4_general_ci LIKE :search) OR (display_name COLLATE utf8mb4_general_ci LIKE :search)
Note: *use either utf8_general_ci or utf8mb4_general_ci depending on the column definition*

*...OR...*

**NEW 2:** SELECT fqda FROM users_fqda WHERE (LOWER(fqda) LIKE LOWER(:search)) OR (LOWER(display_name) LIKE LOWER(:search))

**Comment by PanCakeConnaisseur** [comment]
Hey Kevin, thank you for the tip. This is useful information.

I personally never liked using MySQL for [various reasons](https://help.nextcloud.com/t/tutorial-your-own-mail-server-dovecot-postfix-rspamd-with-tight-nextcloud-on-apache-integration-for-debian/33116/11?u=pancakeconnaisseur), one of them being exactly this very verbose case insensitive search. I only added support for it, because this is what the majority of users use. Still, I don't want to inflate the README.md even more by adding more queries to it. While I am usually on board when it comes to following standards, IMHO its a bad standard if it makes such a simple thing so complicated.

Since I understand that it is still useful information, I just enabled the Wiki function for this repository and would welcome it, if you would add the above information to the [home page](https://github.com/PanCakeConnaisseur/user_backend_sql_raw/wiki). I have already created the "chapters", but feel free to change them. I am sure other MySQL users would be thankful. Thank you.
