### ISSUE TITLE
Is this git dead?

### ISSUE THREAD

**Issue by 1358** [PanCakeConnaisseur/user_backend_sql_raw#42]
There are several open pull requests, there are several requests for NC23 (where it seems as if there is no issue but labled version restriction in the config files, even PR exists!), and the maintainer @PanCakeConnaisseur was last active several months ago?

**Comment by PanCakeConnaisseur** [comment]
This is a hobby project of mine. I have been working on other things that are more important. Therefore it can take a few months for me to update this app. Since I have been applying all NC API changes immediately, the most current version of user_backend_sql_raw is likely good for several subsequent NC releases.
