### ISSUE TITLE
Suddenly error in sql statement with mariadb

### ISSUE THREAD

**Issue by gpgmailencrypt** [PanCakeConnaisseur/user_backend_sql_raw#46]
After working correctly for years I suddenly get an error when trying to restrict external storage to specific users/groups.
The sql code causing the problem is 
`SELECT local_part FROM mailbox WHERE (local_part LIKE '%%') OR (name LIKE '%%') OFFSET 0`
and indeed mariadb denies this code as wrong. After fiddling around mariadb will only accept it with an additional **ROWS** at the end:
`SELECT local_part FROM mailbox WHERE (local_part LIKE '%%') OR (name LIKE '%%') OFFSET 0 ROWS `

I use Ubuntu 22.04 with all current updates and mariadb 10.6.12-MariaDB-0ubuntu0.22.04.1 on Nextcloud 26.0.1
Here's the log:
```
[index] Fehler: PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1 at <<closure>>

0. /var/www/nextcloud/apps/user_backend_sql_raw/lib/UserBackend.php line 118
   PDOStatement->execute()
1. /var/www/nextcloud/apps/user_backend_sql_raw/lib/UserBackend.php line 142
   OCA\UserBackendSqlRaw\UserBackend->getUsers()
2. /var/www/nextcloud/lib/private/User/Manager.php line 335
   OCA\UserBackendSqlRaw\UserBackend->getDisplayNames()
3. /var/www/nextcloud/apps/files_external/ajax/applicable.php line 51
   OC\User\Manager->searchDisplayName()
4. /var/www/nextcloud/lib/private/Route/Route.php line 155
   require_once("/var/www/nextcl ... p")
5. <<closure>>
   OC\Route\Route->OC\Route\{closure}("*** sensitive parameters replaced ***")
6. /var/www/nextcloud/lib/private/Route/Router.php line 324
   call_user_func()
7. /var/www/nextcloud/lib/base.php line 1056
   OC\Route\Router->match()
8. /var/www/nextcloud/index.php line 36
   OC::handleRequest()

```
Any idea why this happens now and how to solve this problem?
Could it relate to a new sql syntax [https://mariadb.com/kb/en/select-offset-fetch/](https://mariadb.com/kb/en/select-offset-fetch/) which was introduced  with version 10.6.0 a few weeks ago?

**Comment by PanCakeConnaisseur** [comment]
I am not sure what is going on there. AFAIU `ROWS` should have no effect in that SQL expression, but I am not an SQL expert.

Independent of that: I have been thinking about dropping MariaDB/MySQL support for a while, because it requires so much extra effort instead of "just working" as PostgreSQL does. Should it stop working, I would rather remove the entire MariaDB code than try to make it work again. I have neither the time nor motivation to support that hacky mess. AFAIK PostgreSQL has long surpassed MariaDB/MySQL in terms of performance and I can only assume people still use MySQL for historical reasons.

I don't claim to be an expert on this subject but just want to explain my motivation for dropping support, should it become necessary.
